= Release notes v.6.2

== Table of Contents

* Remove deprecated PaymentAuthorisationType
* Drop deprecated tables for AIS and PIS authorisations
* Remove deprecated PiisConsentTppAccessType
* Unification of Payment Canc auth-subresources by authorisationId instead of cancellationId

== Remove deprecated PaymentAuthorisationType

Deprecated PaymentAuthorisationType was removed

== Drop deprecated tables for AIS and PIS authorisations

Following deprecated tables were dropped from CMS database:

* ais_consent_authorization
* pis_consent_authorization
* ais_available_sca_method
* pis_available_sca_method

== Remove deprecated PiisConsentTppAccessType

Deprecated PiisConsentTppAccessType was removed

== Unification of Payment Canc auth-subresources by authorisationId instead of cancellationId

From now on, path parameter `cancellationId` has been renamed to `authorisationId` in
`Read the SCA status of the payment cancellation's authorisation (GET)` and `Update PSU data for payment initiation cancellation (PUT)` endpoints `/v1/{payment-service}/{payment-product}/{paymentId}/cancellation-authorisations/{authorisationId}`.

Also in `Get cancellation authorisation sub-resources` endpoint `/v1/{payment-service}/{payment-product}/{paymentId}/cancellation-authorisations` response tag “cancellationIds” has been changed to “authorisationIds”.
