= Release notes v.7.7

== Table of Contents

* Added information about currency conversion to Payment Initiation response
* Fixed Double saving of psu data
* Added currency conversion related information to Update PSU Data response
* Implemented Get Authorisation Sub-resource request for Funds Confirmation Consent

=== Added information about currency conversion to Payment Initiation response

From now on, information about currency conversion is passed through spi level to
Payment Initiation response.

=== Fixed Double saving of psu data

From now on, in all cms psu api requests psu data is saved correctly.

=== Added currency conversion related information to Update PSU Data response

From now on, information about currency conversion related information is added
into update psu data response.

=== Implemented Get Authorisation Sub-resource request for Funds Confirmation Consent

From now on, endpoint `GET /v2/consents/confirmation-of-funds/{consentId}/authorisations` is implemented
and gives response with authorisation identifications list.
