= Release notes v.5.5

== Table of Contents

* Removed deprecated columns TppRedirectUri from TppInfo
* Removed deprecated `PsuIdData` from `confirmConsent`, `rejectConsent`, `revokeConsent` in `CmsPsuAisService`
* Refactoring: Extracted ASPSP Profile web-endpoints into separate module
* Bugfix: incorrect response for start authorisation request with password but without PSU-ID in header Explicit AIS/PIS
* Add supporting standing order report

== Removed deprecated columns TppRedirectUri from TppInfo

From now on, deprecated columns `redirect_uri`, `nok_redirect_uri`, `cancel_redirect_uri`,
`cancel_nok_redirect_uri` are removed from `tpp_info` table in CMS.

== Removed deprecated `PsuIdData` from `confirmConsent`, `rejectConsent`, `revokeConsent` in `CmsPsuAisService`

From now on, deprecated method `authorisePartiallyConsent` is removed from `CmsPsuAisService`
and deprecated headers `psuId`, `psuIdType`, `psuCorporateId`, `psuCorporateIdType` are removed from
`authorisePartiallyConsent` method in `CmsPsuAisController`.

== Refactoring: Extracted ASPSP Profile web-endpoints into separate module

From now on, endpoints for accessing and updating ASPSP Profile are located in `aspsp-profile-web` module.

== Bugfix: incorrect response for start authorisation request with password but without PSU-ID in header Explicit AIS/PIS

From now on, when you try to start authorisation for payment/consent with password and without `PSU-ID` in header,
you'll receive the same response as it would be with `PSU-ID` in header.

== Add supporting standing order report

From now on, it's possible to return standing order report on Get Transaction Status request(`GET /v1/accounts/{{account_id}}/transactions`) in JSON format.

This endpoint is offering a list of all standing orders related to a dedicated payment account ion case of `bookingStatus` parameter equals `information`.
To support the `information` feature is optional for the ASPSP. Error code if not supported.
The query parameters `dateFrom`, `dateTo`, `withBalance`, `deltaList` and `entryReferenceFrom` will be ignored and have no effect on the
result.

In the accept header the `application/JSON` header must be supported, since the standing order report is supported in JSON only within this specification.
