= Release notes v.5.4

== Table of Contents

* Implement support of Multicurrency Accounts
* Read the SCA status return incorrect SCA status after Update PSU data request without PSU-ID in header

== Implement support of Multicurrency Accounts

From now on, XS2A supports flows for multicurrency accounts.
A multicurrency account is an account which is a collection of different sub-accounts which are all addressed by the same account identifier like an IBAN by e.g. payment initiating parties.
The sub-accounts are legally different accounts and they all differ in their currency, balances and transactions.
An account identifier like an IBAN together with a currency always addresses uniquely a sub-account of a multicurrency account.
ASPSP can grant data access to multicurrency account on SUBACCOUNT, AGGREGATION or AGGREGATION_AND_SUBACCOUNT level by setting `multicurrencyAccountLevelSupported` property in ASPSP-Profile.

== Read the SCA status return incorrect SCA status after Update PSU data request without PSU-ID in header

From now on, if you try to update PSU data without PSU-ID in header, `scaStatus` from response will be persisted
into database, and when you'll try to get it, the response will contain proper `scaStatus`.
